config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :place_records
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place_record.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: place_records
#
#  id         :bigint(8)        not null, primary key
#  comment    :text
#  lat        :float
#  lon        :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PlaceRecord < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/place_records_controller.rb
# frozen_string_literal: true

class PlaceRecordsController < ApplicationController
  before_action :set_place_record, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except: :create

  # GET /place_records
  # GET /place_records.json
  def index
    @place_records = PlaceRecord.order(created_at: :desc)
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @place_records.to_json }
    end
  end

  # GET /place_records/1
  # GET /place_records/1.json
  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @place_record.to_json }
    end
  end

  # GET /place_records/new
  def new
    @place_record = PlaceRecord.new
  end

  # GET /place_records/1/edit
  def edit
  end

  # POST /place_records
  # POST /place_records.json
  def create
    @place_record = PlaceRecord.new(place_record_params)

    respond_to do |format|
      if @place_record.save
        format.html { redirect_to @place_record, notice: "PlaceRecord was successfully created." }
        format.json { render json: {status: :ok}, status: :created, location: @place_record }
      else
        format.html { render :new }
        format.json { render json: @place_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /place_records/1
  def update
    if @place_record.update(place_record_params)
      redirect_to @place_record, notice: "Place record was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /place_records/1
  def destroy
    @place_record.destroy
    redirect_to place_records_url, notice: "Place record was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place_record
      @place_record = PlaceRecord.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def place_record_params
      params.require(:place_record).permit(:lat, :lon, :comment)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/place_records_helper.rb
# frozen_string_literal: true

module PlaceRecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>位置情報保存</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/place_records/_form.html.haml
= form_for @place_record do |f|
  - if @place_record.errors.any?
    #error_explanation
      %h2= "#{pluralize(@place_record.errors.count, "error")} prohibited this place_record from being saved:"
      %ul
        - @place_record.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :lat
    = f.text_field :lat
  .field
    = f.label :lon
    = f.text_field :lon
  .field
    = f.label :comment
    = f.text_area :comment
  .actions
    = f.submit 'Save'

app/views/place_records/edit.html.haml
%h1 Editing place_record

= render 'form'

= link_to 'Show', @place_record
\|
= link_to 'Back', place_records_path

app/views/place_records/index.html.haml
%h1 Listing place_records

%table
  %thead
    %tr
      %th Lat
      %th Lon
      %th Comment
      %th
      %th
      %th

  %tbody
    - @place_records.each do |place_record|
      %tr
        %td= place_record.lat
        %td= place_record.lon
        %td= place_record.comment
        %td= link_to 'Show', place_record
        %td= link_to 'Edit', edit_place_record_path(place_record)
        %td= link_to 'Destroy', place_record, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Place record', new_place_record_path

app/views/place_records/new.html.haml
%h1 New place_record

= render 'form'

= link_to 'Back', place_records_path

app/views/place_records/show.html.haml
%p#notice= notice

%p
  %b Lat:
  = @place_record.lat
%p
  %b Lon:
  = @place_record.lon
%p
  %b Comment:
  = @place_record.comment

= link_to 'Edit', edit_place_record_path(@place_record)
\|
= link_to 'Back', place_records_path